/**
 * PRAgent - PR作成 Agent
 *
 * Branch作成 → Files commit → Draft PR作成
 * Conventional Commits 準拠のコミットメッセージ生成
 */
import { GitHubClient } from "../clients/GitHubClient.js";

export interface PRInput {
  issueNumber: number;
  owner: string;
  repository: string;
  baseBranch?: string;
  files: Array<{
    path: string;
    content: string;
    action: "create" | "modify" | "delete";
  }>;
  qualityReport: {
    qualityScore: number;
    passed: boolean;
    coverage: number;
    issues: Array<{
      severity: string;
      file: string;
      line?: number;
      message: string;
    }>;
    suggestions: string[];
  };
  githubClient?: GitHubClient;
}

export interface PROutput {
  success: boolean;
  data?: {
    number: number;
    url: string;
    branch: string;
    status: string;
  };
  error?: string;
}

interface PRAgentConfig {
  githubToken?: string;
}

export class PRAgent {
  private githubClient?: GitHubClient;

  constructor(config?: PRAgentConfig) {
    if (config?.githubToken) {
      this.githubClient = new GitHubClient(config.githubToken);
    }
  }

  async create(input: PRInput): Promise<PROutput> {
    try {
      const githubClient = input.githubClient || this.githubClient;
      const baseBranch = input.baseBranch || "main";

      // 1. Feature branch名生成
      const branchName = this.generateBranchName(input.issueNumber);

      // 2. Branch作成
      await this.createBranch(
        input.owner,
        input.repository,
        branchName,
        baseBranch,
        githubClient
      );

      // 3. Files commit
      await this.commitFiles(
        input.owner,
        input.repository,
        branchName,
        input.files,
        this.generateCommitMessage(input),
        githubClient
      );

      // 4. Draft PR作成
      const pr = await this.createPullRequest({
        owner: input.owner,
        repository: input.repository,
        base: baseBranch,
        head: branchName,
        title: this.generatePRTitle(input),
        body: this.generatePRBody(input),
        draft: true,
        githubClient,
      });

      return { success: true, data: pr };
    } catch (error) {
      return {
        success: false,
        error:
          error instanceof Error ? error.message : "Unknown error occurred",
      };
    }
  }

  private generateBranchName(issueNumber: number): string {
    const timestamp = Date.now();
    return `agent/issue-${issueNumber}-${timestamp}`;
  }

  private async createBranch(
    owner: string,
    repository: string,
    branchName: string,
    baseBranch: string,
    githubClient?: GitHubClient
  ): Promise<void> {
    if (githubClient) {
      await githubClient.createBranch(owner, repository, branchName, baseBranch);
    } else {
      console.log(
        `[PRAgent] Would create branch: ${branchName} from ${baseBranch}`
      );
    }
  }

  private async commitFiles(
    owner: string,
    repository: string,
    branch: string,
    files: Array<{ path: string; content: string }>,
    message: string,
    githubClient?: GitHubClient
  ): Promise<void> {
    if (githubClient) {
      await githubClient.commitFiles({
        owner,
        repo: repository,
        branch,
        files: files.map((f) => ({ path: f.path, content: f.content })),
        message,
      });
    } else {
      console.log(
        `[PRAgent] Would commit ${files.length} files to ${branch}: ${message}`
      );
    }
  }

  private generateCommitMessage(input: PRInput): string {
    const type = this.inferCommitType(input.files);
    const scope = this.inferScope(input.files);
    const subject = `autonomous implementation for issue #${input.issueNumber}`;
    const body = `Quality Score: ${input.qualityReport.qualityScore}/100\nCoverage: ${input.qualityReport.coverage}%\nFiles changed: ${input.files.length}`;
    const footer = `Closes #${input.issueNumber}\n\nGenerated by Miyabi Autonomous Agent`;
    return `${type}${scope ? `(${scope})` : ""}: ${subject}\n\n${body}\n\n${footer}`;
  }

  private inferCommitType(
    files: Array<{ action: string }>
  ): string {
    const actions = files.map((f) => f.action);
    if (actions.includes("delete")) return "refactor";
    if (actions.every((a) => a === "create")) return "feat";
    if (actions.some((a) => a === "modify")) return "fix";
    return "feat";
  }

  private inferScope(files: Array<{ path: string }>): string {
    if (files.length === 0) return "";
    const firstFile = files[0].path;
    const parts = firstFile.split("/");
    if (parts.length > 1 && parts[0] === "src") return parts[1];
    return parts[0];
  }

  private generatePRTitle(input: PRInput): string {
    const type = this.inferCommitType(input.files);
    return `${type}: autonomous implementation for issue #${input.issueNumber}`;
  }

  private generatePRBody(input: PRInput): string {
    const passedEmoji = input.qualityReport.passed ? "✅" : "❌";
    const issuesSection =
      input.qualityReport.issues.length > 0
        ? `\n### Issues Found\n${input.qualityReport.issues
            .map(
              (issue) =>
                `- [${issue.severity}] ${issue.file}${issue.line ? `:${issue.line}` : ""} - ${issue.message}`
            )
            .join("\n")}\n`
        : "";

    const suggestionsSection =
      input.qualityReport.suggestions.length > 0
        ? `\n### Suggestions\n${input.qualityReport.suggestions.map((s) => `- ${s}`).join("\n")}\n`
        : "";

    return `## Autonomous Agent Implementation

**Issue**: #${input.issueNumber}
**Quality Score**: ${input.qualityReport.qualityScore}/100
**Coverage**: ${input.qualityReport.coverage}%

### Quality Report
${passedEmoji} Quality check ${input.qualityReport.passed ? "passed" : "failed"}
${issuesSection}${suggestionsSection}
### Files Changed
${input.files.map((f) => `- [${f.action}] \`${f.path}\``).join("\n")}

### Checklist
- [x] Code generated
- [x] Tests generated
- [x] Quality check (>=80): ${input.qualityReport.qualityScore}/100
- [ ] Manual review required
- [ ] Ready to merge

Closes #${input.issueNumber}

---
Generated by Miyabi Autonomous Agent`;
  }

  private async createPullRequest(params: {
    owner: string;
    repository: string;
    base: string;
    head: string;
    title: string;
    body: string;
    draft: boolean;
    githubClient?: GitHubClient;
  }): Promise<{ number: number; url: string; branch: string; status: string }> {
    if (params.githubClient) {
      const prInfo = await params.githubClient.createPullRequest({
        owner: params.owner,
        repo: params.repository,
        title: params.title,
        body: params.body,
        head: params.head,
        base: params.base,
        draft: params.draft,
      });
      return {
        number: prInfo.number,
        url: prInfo.html_url,
        branch: params.head,
        status: params.draft ? "draft" : "open",
      };
    }

    // Mock
    const mockPrNumber = Math.floor(Math.random() * 1000) + 1;
    return {
      number: mockPrNumber,
      url: `https://github.com/${params.owner}/${params.repository}/pull/${mockPrNumber}`,
      branch: params.head,
      status: "draft",
    };
  }
}
